#!/bin/bash

Home="/data/tboschi/NewSupershock/"

cd $Home

if [ $1 -eq 1 ]
then
	Channel="nEE"
elif [ $1 -eq 2 ]
then
	Channel="nEM"
elif [ $1 -eq 3 ]
#then
#	Channel="nME"
#elif [ $1 -eq 4 ]
then
	Channel="nMM"
elif [ $1 -eq 4 ]
then
	Channel="nET"
elif [ $1 -eq 5 ]
#then
#	Channel="nTE"
#elif [ $1 -eq 7 ]
then
	Channel="nMT"
elif [ $1 -eq 6 ]
#then
#	Channel="nTM"
#elif [ $1 -eq 9 ]
then
	Channel="nPI0"
elif [ $1 -eq 7 ]
then
	Channel="EPI"
elif [ $1 -eq 8 ]
then
	Channel="MPI"
elif [ $1 -eq 9 ]
then
	Channel="TPI"
elif [ $1 -eq 10 ]
then
	Channel="EKA"
elif [ $1 -eq 11 ]
then
	Channel="MKA"
elif [ $1 -eq 12 ]
then
	Channel="nRHO0"
elif [ $1 -eq 13 ]
then
	Channel="ERHO"
elif [ $1 -eq 14 ]
then
	Channel="MRHO"
elif [ $1 -eq 15 ]
then
	Channel="EKAx"
elif [ $1 -eq 16 ]
then
	Channel="MKAx"
elif [ $1 -eq 17 ]
then
	Channel="nOMEGA"
elif [ $1 -eq 18 ]
then
	Channel="nETA"
elif [ $1 -eq 19 ]
then
	Channel="nETAi"
elif [ $1 -eq 20 ]
then
	Channel="nPHI"
elif [ $1 -eq 21 ]
then
	Channel="ECHARM"
elif [ $1 -eq 22 ]
then
	Channel="nGAMMA"
elif [ $1 -eq 23 ]
then
	Channel="ExpALL"
else
	echo "Invalid argument: " $1
fi

echo $Channel
