#!/bin/bash

cd /mt/home/tboschi/Templates/MCflux/Supershock

./bin/Coupler -A Exclusion/LAr/LAr_MUPI_M_0.dat -B Exclusion/FGT/FGT_MUPI_M_0.dat -o Exclusion/Couple/MUPI_M_0.dat
./bin/Coupler -A Exclusion/LAr/LAr_nMUMU_M_0.dat -B Exclusion/FGT/FGT_nMUMU_M_0.dat -o Exclusion/Couple/nMUMU_M_0.dat
./bin/Coupler -A Exclusion/LAr/LAr_nMUE_M_0.dat -B Exclusion/FGT/FGT_nMUE_M_0.dat -o Exclusion/Couple/nMUE_M_0.dat
./bin/Coupler -A Exclusion/LAr/LAr_nEE_M_0.dat -B Exclusion/FGT/FGT_nEE_M_0.dat -o Exclusion/Couple/nEE_M_0.dat
./bin/Coupler -A Exclusion/LAr/LAr_nPI0_M_0.dat -B Exclusion/FGT/FGT_nPI0_M_0.dat -o Exclusion/Couple/nPI0_M_0.dat
./bin/Coupler -A Exclusion/LAr/LAr_nGAMMA_M_0.dat -B Exclusion/FGT/FGT_nGAMMA_M_0.dat -o Exclusion/Couple/nGAMMA_M_0.dat

./bin/Coupler -A Exclusion/LAr/LAr_EPI_E_0.dat -B Exclusion/FGT/FGT_EPI_E_0.dat -o Exclusion/Couple/EPI_E_0.dat
./bin/Coupler -A Exclusion/LAr/LAr_nMUMU_E_0.dat -B Exclusion/FGT/FGT_nMUMU_E_0.dat -o Exclusion/Couple/nMUMU_E_0.dat
./bin/Coupler -A Exclusion/LAr/LAr_nMUE_E_0.dat -B Exclusion/FGT/FGT_nMUE_E_0.dat -o Exclusion/Couple/nMUE_E_0.dat
./bin/Coupler -A Exclusion/LAr/LAr_nEE_E_0.dat -B Exclusion/FGT/FGT_nEE_E_0.dat -o Exclusion/Couple/nEE_E_0.dat
./bin/Coupler -A Exclusion/LAr/LAr_nPI0_E_0.dat -B Exclusion/FGT/FGT_nPI0_E_0.dat -o Exclusion/Couple/nPI0_E_0.dat
./bin/Coupler -A Exclusion/LAr/LAr_nGAMMA_E_0.dat -B Exclusion/FGT/FGT_nGAMMA_E_0.dat -o Exclusion/Couple/nGAMMA_E_0.dat

