#!/bin/bash

cd /mt/home/tboschi/Templates/MCflux/Supershock

./bin/Plotter -i Exclusion/LAr_$1/LAr_MUPI_M_0.dat -o Exclusion/Plot_LAr_$1/MUPI_M_0.dat -t 2.44
./bin/Plotter -i Exclusion/LAr_$1/LAr_nMUMU_M_0.dat -o Exclusion/Plot_LAr_$1/nMUMU_M_0.dat -t 2.44
./bin/Plotter -i Exclusion/LAr_$1/LAr_nMUE_M_0.dat -o Exclusion/Plot_LAr_$1/nMUE_M_0.dat -t 2.44
./bin/Plotter -i Exclusion/LAr_$1/LAr_nEE_M_0.dat -o Exclusion/Plot_LAr_$1/nEE_M_0.dat -t 2.44
./bin/Plotter -i Exclusion/LAr_$1/LAr_nGAMMA_M_0.dat -o Exclusion/Plot_LAr_$1/nGAMMA_M_0.dat -t 2.44
./bin/Plotter -i Exclusion/LAr_$1/LAr_nPI0_M_0.dat -o Exclusion/Plot_LAr_$1/nPI0_M_0.dat -t 2.44

./bin/Plotter -i Exclusion/LAr_$1/LAr_EPI_E_0.dat -o Exclusion/Plot_LAr_$1/EPI_E_0.dat -t 2.44
./bin/Plotter -i Exclusion/LAr_$1/LAr_nMUMU_E_0.dat -o Exclusion/Plot_LAr_$1/nMUMU_E_0.dat -t 2.44
./bin/Plotter -i Exclusion/LAr_$1/LAr_nMUE_E_0.dat -o Exclusion/Plot_LAr_$1/nMUE_E_0.dat -t 2.44
./bin/Plotter -i Exclusion/LAr_$1/LAr_nEE_E_0.dat -o Exclusion/Plot_LAr_$1/nEE_E_0.dat -t 2.44
./bin/Plotter -i Exclusion/LAr_$1/LAr_nGAMMA_E_0.dat -o Exclusion/Plot_LAr_$1/nGAMMA_E_0.dat -t 2.44
./bin/Plotter -i Exclusion/LAr_$1/LAr_nPI0_E_0.dat -o Exclusion/Plot_LAr_$1/nPI0_E_0.dat -t 2.44
