#!/bin/bash

Home="/mt/home/tboschi/scratch/Supershock"

cd $Home
Config="config"
Exec="./bin/MegaPlot"
#ND="LAr"
ND="FGT"

#e -> M
if [ $1 -eq 0 ]
then
	Channel="MUPI"
	Type=1
	Flag=0
elif [ $1 -eq 1 ]
then
	Channel="nMUE"
	Type=1
	Flag=0
elif [ $1 -eq 2 ]
then
	Channel="nEE"
	Type=2
	Flag=0
elif [ $1 -eq 3 ]
then
	Channel="nMUMU"
	Type=2
	Flag=0
#e -> T
elif [ $1 -eq 4 ]
then
	Channel="nEE"
	Type=2
	Flag=1
elif [ $1 -eq 5 ]
then
	Channel="nMUMU"
	Type=2
	Flag=1
#m -> E
elif [ $1 -eq 6 ]
then
	Channel="EPI"
	Type=1
	Flag=2
elif [ $1 -eq 7 ]
then
	Channel="nEMU"
	Type=1
	Flag=2
elif [ $1 -eq 8 ]
then
	Channel="nEE"
	Type=2
	Flag=2
elif [ $1 -eq 9 ]
then
	Channel="nMUMU"
	Type=2
	Flag=2
#m -> T
elif [ $1 -eq 10 ]
then
	Channel="nEE"
	Type=2
	Flag=3
elif [ $1 -eq 11 ]
then
	Channel="nMUMU"
	Type=2
	Flag=3
#t -> E
elif [ $1 -eq 12 ]
then
	Channel="EPI"
	Type=1
	Flag=4
elif [ $1 -eq 13 ]
then
	Channel="nEE"
	Type=2
	Flag=4
elif [ $1 -eq 14 ]
then
	Channel="nMUMU"
	Type=2
	Flag=4
#t -> M
elif [ $1 -eq 15 ]
then
	Channel="MUPI"
	Type=1
	Flag=5
elif [ $1 -eq 16 ]
then
	Channel="nEE"
	Type=2
	Flag=5
elif [ $1 -eq 17 ]
then
	Channel="nMUMU"
	Type=2
	Flag=5
else
	echo "Invalid argument: " $1
fi



if [ $Flag -eq 0 ]
then
	A="e"
	B="M"
elif [ $Flag -eq 1 ]
then
	A="e"
	B="T"
elif [ $Flag -eq 2 ]
then
	A="m"
	B="E"
elif [ $Flag -eq 3 ]
then
	A="m"
	B="T"
elif [ $Flag -eq 4 ]
then
	A="t"
	B="E"
elif [ $Flag -eq 5 ]
then
	A="t"
	B="M"
else
	echo "Invalid argument: " $1
fi

Input="Exclusion/Mix/"$ND"_"$Channel"_"$A"_"$B".dat"
Output="Exclusion/Plot_Mix/Plot_"$ND"_"$Channel"_"$A"_"$B".dat"
echo $Exec -i $Input -o $Output -t $Type
$Exec -i $Input -o $Output -t $Type
