#!/bin/bash

cd /mt/home/tboschi/Templates/MCflux/Supershock

#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.250 -M -c MUPI -o Simulation/LAr/sign_LAr_MUPI_250_M.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.300 -M -c MUPI -o Simulation/LAr/sign_LAr_MUPI_300_M.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.350 -M -c MUPI -o Simulation/LAr/sign_LAr_MUPI_350_M.root -n 10000

#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.250 -M -c nMUMU -o Simulation/LAr/sign_LAr_nMUMU_250_M.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.300 -M -c nMUMU -o Simulation/LAr/sign_LAr_nMUMU_300_M.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.350 -M -c nMUMU -o Simulation/LAr/sign_LAr_nMUMU_350_M.root -n 10000

#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.150 -M -c nMUE -o Simulation/LAr/sign_LAr_nMUE_150_M.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.200 -M -c nMUE -o Simulation/LAr/sign_LAr_nMUE_200_M.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.250 -M -c nMUE -o Simulation/LAr/sign_LAr_nMUE_250_M.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.300 -M -c nMUE -o Simulation/LAr/sign_LAr_nMUE_300_M.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.350 -M -c nMUE -o Simulation/LAr/sign_LAr_nMUE_350_M.root -n 10000

#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.050 -M -c nEE -o Simulation/LAr/sign_LAr_nEE_050_M.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.100 -M -c nEE -o Simulation/LAr/sign_LAr_nEE_100_M.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.150 -M -c nEE -o Simulation/LAr/sign_LAr_nEE_150_M.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.200 -M -c nEE -o Simulation/LAr/sign_LAr_nEE_200_M.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.250 -M -c nEE -o Simulation/LAr/sign_LAr_nEE_250_M.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.300 -M -c nEE -o Simulation/LAr/sign_LAr_nEE_300_M.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.350 -M -c nEE -o Simulation/LAr/sign_LAr_nEE_350_M.root -n 10000

#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.050 -M -c nGAMMA -o Simulation/LAr/sign_LAr_nGAMMA_050_M.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.100 -M -c nGAMMA -o Simulation/LAr/sign_LAr_nGAMMA_100_M.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.150 -M -c nGAMMA -o Simulation/LAr/sign_LAr_nGAMMA_150_M.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.200 -M -c nGAMMA -o Simulation/LAr/sign_LAr_nGAMMA_200_M.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.250 -M -c nGAMMA -o Simulation/LAr/sign_LAr_nGAMMA_250_M.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.300 -M -c nGAMMA -o Simulation/LAr/sign_LAr_nGAMMA_300_M.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.350 -M -c nGAMMA -o Simulation/LAr/sign_LAr_nGAMMA_350_M.root -n 10000

#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.150 -M -c nPI0 -o Simulation/LAr/sign_LAr_nPI0_150_M.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.200 -M -c nPI0 -o Simulation/LAr/sign_LAr_nPI0_200_M.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.250 -M -c nPI0 -o Simulation/LAr/sign_LAr_nPI0_250_M.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.300 -M -c nPI0 -o Simulation/LAr/sign_LAr_nPI0_300_M.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.350 -M -c nPI0 -o Simulation/LAr/sign_LAr_nPI0_350_M.root -n 10000


#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.150 -E -c EPI -o Simulation/LAr/sign_LAr_EPI_150_E.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.200 -E -c EPI -o Simulation/LAr/sign_LAr_EPI_200_E.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.250 -E -c EPI -o Simulation/LAr/sign_LAr_EPI_250_E.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.300 -E -c EPI -o Simulation/LAr/sign_LAr_EPI_300_E.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.350 -E -c EPI -o Simulation/LAr/sign_LAr_EPI_350_E.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.400 -E -c EPI -o Simulation/LAr/sign_LAr_EPI_400_E.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.450 -E -c EPI -o Simulation/LAr/sign_LAr_EPI_450_E.root -n 10000

#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.250 -E -c nMUMU -o Simulation/LAr/sign_LAr_nMUMU_250_E.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.300 -E -c nMUMU -o Simulation/LAr/sign_LAr_nMUMU_300_E.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.350 -E -c nMUMU -o Simulation/LAr/sign_LAr_nMUMU_350_E.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.400 -E -c nMUMU -o Simulation/LAr/sign_LAr_nMUMU_400_E.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.450 -E -c nMUMU -o Simulation/LAr/sign_LAr_nMUMU_450_E.root -n 10000

#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.150 -E -c nEMU -o Simulation/LAr/sign_LAr_nMUE_150_E.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.200 -E -c nEMU -o Simulation/LAr/sign_LAr_nMUE_200_E.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.250 -E -c nEMU -o Simulation/LAr/sign_LAr_nMUE_250_E.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.300 -E -c nEMU -o Simulation/LAr/sign_LAr_nMUE_300_E.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.350 -E -c nEMU -o Simulation/LAr/sign_LAr_nMUE_350_E.root -n 10000
./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.400 -E -c nEMU -o Simulation/LAr/sign_LAr_nMUE_400_E.root -n 10000
./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.450 -E -c nEMU -o Simulation/LAr/sign_LAr_nMUE_450_E.root -n 10000

#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.050 -E -c nEE -o Simulation/LAr/sign_LAr_nEE_050_E.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.100 -E -c nEE -o Simulation/LAr/sign_LAr_nEE_100_E.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.150 -E -c nEE -o Simulation/LAr/sign_LAr_nEE_150_E.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.200 -E -c nEE -o Simulation/LAr/sign_LAr_nEE_200_E.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.250 -E -c nEE -o Simulation/LAr/sign_LAr_nEE_250_E.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.300 -E -c nEE -o Simulation/LAr/sign_LAr_nEE_300_E.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.350 -E -c nEE -o Simulation/LAr/sign_LAr_nEE_350_E.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.400 -E -c nEE -o Simulation/LAr/sign_LAr_nEE_400_E.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.450 -E -c nEE -o Simulation/LAr/sign_LAr_nEE_450_E.root -n 10000

#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.050 -E -c nGAMMA -o Simulation/LAr/sign_LAr_nGAMMA_050_E.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.100 -E -c nGAMMA -o Simulation/LAr/sign_LAr_nGAMMA_100_E.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.150 -E -c nGAMMA -o Simulation/LAr/sign_LAr_nGAMMA_150_E.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.200 -E -c nGAMMA -o Simulation/LAr/sign_LAr_nGAMMA_200_E.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.250 -E -c nGAMMA -o Simulation/LAr/sign_LAr_nGAMMA_250_E.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.300 -E -c nGAMMA -o Simulation/LAr/sign_LAr_nGAMMA_300_E.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.350 -E -c nGAMMA -o Simulation/LAr/sign_LAr_nGAMMA_350_E.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.400 -E -c nGAMMA -o Simulation/LAr/sign_LAr_nGAMMA_400_E.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.450 -E -c nGAMMA -o Simulation/LAr/sign_LAr_nGAMMA_450_E.root -n 10000

#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.150 -E -c nPI0 -o Simulation/LAr/sign_LAr_nPI0_150_E.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.200 -E -c nPI0 -o Simulation/LAr/sign_LAr_nPI0_200_E.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.250 -E -c nPI0 -o Simulation/LAr/sign_LAr_nPI0_250_E.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.300 -E -c nPI0 -o Simulation/LAr/sign_LAr_nPI0_300_E.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.350 -E -c nPI0 -o Simulation/LAr/sign_LAr_nPI0_350_E.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.400 -E -c nPI0 -o Simulation/LAr/sign_LAr_nPI0_400_E.root -n 10000
#./bin/Simulation -s config/SMConfig -f config/FluxConfig -d config/ND_LAr -m 0.450 -E -c nPI0 -o Simulation/LAr/sign_LAr_nPI0_450_E.root -n 10000
