#!/bin/bash

cd /mt/home/tboschi/scratch/Supershock

./bin/Plotter -i Exclusion/FGT/FGT_MUPI_M_C.dat -o Exclusion/Plot_FGT/MUPI_M_C.dat -t 2.44
./bin/Plotter -i Exclusion/FGT/FGT_nMUMU_M_C.dat -o Exclusion/Plot_FGT/nMUMU_M_C.dat -t 2.44
./bin/Plotter -i Exclusion/FGT/FGT_nMUE_M_C.dat -o Exclusion/Plot_FGT/nMUE_M_C.dat -t 2.44
./bin/Plotter -i Exclusion/FGT/FGT_nEE_M_C.dat -o Exclusion/Plot_FGT/nEE_M_C.dat -t 2.44
./bin/Plotter -i Exclusion/FGT/FGT_nGAMMA_M_C.dat -o Exclusion/Plot_FGT/nGAMMA_M_C.dat -t 2.44
./bin/Plotter -i Exclusion/FGT/FGT_nPI0_M_C.dat -o Exclusion/Plot_FGT/nPI0_M_C.dat -t 2.44

./bin/Plotter -i Exclusion/FGT/FGT_EPI_E_C.dat -o Exclusion/Plot_FGT/EPI_E_C.dat -t 2.44
./bin/Plotter -i Exclusion/FGT/FGT_nMUMU_E_C.dat -o Exclusion/Plot_FGT/nMUMU_E_C.dat -t 2.44
./bin/Plotter -i Exclusion/FGT/FGT_nMUE_E_C.dat -o Exclusion/Plot_FGT/nMUE_E_C.dat -t 2.44
./bin/Plotter -i Exclusion/FGT/FGT_nEE_E_C.dat -o Exclusion/Plot_FGT/nEE_E_C.dat -t 2.44
./bin/Plotter -i Exclusion/FGT/FGT_nGAMMA_E_C.dat -o Exclusion/Plot_FGT/nGAMMA_E_C.dat -t 2.44
./bin/Plotter -i Exclusion/FGT/FGT_nPI0_E_C.dat -o Exclusion/Plot_FGT/nPI0_E_C.dat -t 2.44
