#!/bin/bash

cd /mt/home/tboschi/Templates/MCflux/Supershock

./bin/XSec -P -M 0.0 -o CrossSection/xsec_P_00.dat
./bin/XSec -P -M 0.2 -o CrossSection/xsec_P_02.dat
./bin/XSec -P -M 0.4 -o CrossSection/xsec_P_04.dat
./bin/XSec -P -M 0.6 -o CrossSection/xsec_P_06.dat
./bin/XSec -P -M 0.8 -o CrossSection/xsec_P_08.dat
./bin/XSec -P -M 1.0 -o CrossSection/xsec_P_10.dat
./bin/XSec -P -M 1.2 -o CrossSection/xsec_P_12.dat
./bin/XSec -P -M 1.4 -o CrossSection/xsec_P_14.dat
./bin/XSec -P -M 1.6 -o CrossSection/xsec_P_16.dat
./bin/XSec -P -M 1.8 -o CrossSection/xsec_P_18.dat
./bin/XSec -P -M 2.0 -o CrossSection/xsec_P_20.dat
./bin/XSec -P -M 2.5 -o CrossSection/xsec_P_25.dat
./bin/XSec -P -M 3.0 -o CrossSection/xsec_P_30.dat
./bin/XSec -P -M 3.5 -o CrossSection/xsec_P_35.dat
./bin/XSec -P -M 4.0 -o CrossSection/xsec_P_40.dat
./bin/XSec -P -M 4.5 -o CrossSection/xsec_P_45.dat
./bin/XSec -P -M 5.0 -o CrossSection/xsec_P_50.dat

./bin/XSec -N -M 0.0 -o CrossSection/xsec_N_00.dat
./bin/XSec -N -M 0.2 -o CrossSection/xsec_N_02.dat
./bin/XSec -N -M 0.4 -o CrossSection/xsec_N_04.dat
./bin/XSec -N -M 0.6 -o CrossSection/xsec_N_06.dat
./bin/XSec -N -M 0.8 -o CrossSection/xsec_N_08.dat
./bin/XSec -N -M 1.0 -o CrossSection/xsec_N_10.dat
./bin/XSec -N -M 1.2 -o CrossSection/xsec_N_12.dat
./bin/XSec -N -M 1.4 -o CrossSection/xsec_N_14.dat
./bin/XSec -N -M 1.6 -o CrossSection/xsec_N_16.dat
./bin/XSec -N -M 1.8 -o CrossSection/xsec_N_18.dat
./bin/XSec -N -M 2.0 -o CrossSection/xsec_N_20.dat
./bin/XSec -N -M 2.5 -o CrossSection/xsec_N_25.dat
./bin/XSec -N -M 3.0 -o CrossSection/xsec_N_30.dat
./bin/XSec -N -M 3.5 -o CrossSection/xsec_N_35.dat
./bin/XSec -N -M 4.0 -o CrossSection/xsec_N_40.dat
./bin/XSec -N -M 4.5 -o CrossSection/xsec_N_45.dat
./bin/XSec -N -M 5.0 -o CrossSection/xsec_N_50.dat
