#!/bin/bash

cd /mt/home/tboschi/Templates/MCflux/Supershock

./bin/Rate -d config/ND_FGT2 -x ../numu_argon_xsec.root -f data/NuMu_0.root -o data/Rate_FGT2_NuMu.dat
./bin/Rate -d config/ND_FGT2 -x ../nue_argon_xsec.root -f data/NuE_0.root -o data/Rate_FGT2_NuE.dat
./bin/Rate -d config/ND_FGT2 -x ../nubar_argon_xsec.root -f data/NuBar_0.root -o data/Rate_FGT2_NuBar.dat
