#!/bin/bash

cd /mt/home/tboschi/Templates/MCflux/Supershock

./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_nnn_T.dat -c nnn  	-T 
./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_nGAMMA_T.dat -c nGAMMA	-T
./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_nEE_T.dat -c nEE   	-T
#./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_nEMU_T.dat -c nEMU  	-T
#./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_nMUE_T.dat -c nMUE  	-T
./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_nMUMU_T.dat -c nMUMU 	-T
#./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_nET_T.dat -c nET   	-T
./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_nTE_T.dat -c nTE   	-T
#./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_nMUT_T.dat -c nMUT  	-T
./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_nTMU_T.dat -c nTMU  	-T
./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_nPI0_T.dat -c nPI0  	-T
#./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_EPI_T.dat -c EPI   	-T
#./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_MUPI_T.dat -c MUPI  	-T
./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_TPI_T.dat -c TPI   	-T
#./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_EKA_T.dat -c EKA   	-T
#./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_MUKA_T.dat -c MUKA  	-T
./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_nRHO0_T.dat -c nRHO0 	-T
#./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_ERHO_T.dat -c ERHO  	-T
#./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_MURHO_T.dat -c MURHO 	-T
#./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_EKAx_T.dat -c EKAx  	-T
./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_nKA0x_T.dat -c nKA0x 	-T
#./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_MUKAx_T.dat -c MUKAx 	-T
./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_nOMEGA_T.dat -c nOMEGA	-T
./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_nETA_T.dat -c nETA  	-T
./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_nETAi_T.dat -c nETAi 	-T
./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_nPHI_T.dat -c nPHI  	-T
#./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_ECHARM_T.dat -c ECHARM	-T
