#!/bin/bash

cd /mt/home/tboschi/Templates/MCflux/Supershock

./bin/Plotter -i Exclusion/LAr/LAr_MUPI_M_B.dat -o Exclusion/Plot_LAr/MUPI_M_B.dat -t -0.1082 -m 219.96 -A 0.25 -B 0.35
./bin/Plotter -i Exclusion/LAr/LAr_nEE_M_B.dat -o Exclusion/Plot_LAr/nEE_M_B.dat -t 35.9329 -m 88.0119 -A 0.05 -B 0.35
./bin/Plotter -i Exclusion/LAr/LAr_nMUE_M_B.dat -o Exclusion/Plot_LAr/nMUE_M_B.dat -t 41.1923 -m 14.9867 -A 0.15 -B 0.35
./bin/Plotter -i Exclusion/LAr/LAr_nMUMU_M_B.dat -o Exclusion/Plot_LAr/nMUMU_M_B.dat -t 59.5377 -m 58.0274 -A 0.25 -B 0.35
./bin/Plotter -i Exclusion/LAr/LAr_nGAMMA_M_B.dat -o Exclusion/Plot_LAr/nGAMMA_M_B.dat -t 66.8106 -m -68.1774 -A 0.05 -B 0.35
./bin/Plotter -i Exclusion/LAr/LAr_nPI0_M_B.dat -o Exclusion/Plot_LAr/nPI0_M_B.dat -t -38.3797 -m 348.567 -A 0.15 -B 0.35

./bin/Plotter -i Exclusion/LAr/LAr_EPI_E_B.dat -o Exclusion/Plot_LAr/EPI_E_B.dat -t 19.7923 -m 21.0791 -A 0.15 -B 0.45
./bin/Plotter -i Exclusion/LAr/LAr_nEE_E_B.dat -o Exclusion/Plot_LAr/nEE_E_B.dat -t 35.9329 -m 88.0119 -A 0.05 -B 0.45
./bin/Plotter -i Exclusion/LAr/LAr_nMUE_E_B.dat -o Exclusion/Plot_LAr/nMUE_E_B.dat -t 41.1923 -m 14.9867 -A 0.15 -B 0.45
./bin/Plotter -i Exclusion/LAr/LAr_nMUMU_E_B.dat -o Exclusion/Plot_LAr/nMUMU_E_B.dat -t 59.5377 -m 58.0274 -A 0.25 -B 0.45
./bin/Plotter -i Exclusion/LAr/LAr_nGAMMA_E_B.dat -o Exclusion/Plot_LAr/nGAMMA_E_B.dat -t 66.8106 -m -68.1774 -A 0.05 -B 0.45
./bin/Plotter -i Exclusion/LAr/LAr_nPI0_E_B.dat -o Exclusion/Plot_LAr/nPI0_E_B.dat -t -38.3797 -m 348.567 -A 0.15 -B 0.45

