#!/bin/bash

Config="config"

Exec="./bin/Simulation"

#Channel=$(./EchoChannel $1)
Opt0="-d config/ND_Full -f config/FluxConfig"

Chan1={"nEE"}
Chan2={"nEM"}
Chan3={"nME"}
Chan4={"nMM"}
Chan5={"nGAMMA"}
Chan6={"nPI0"}
Chan7={"EPI"}
Chan8={"MPI"}

ChanArr={"$Chan1" "$Chan2" "$Chan3" "$Chan4" "$Chan5" "$Chan6" "$Chan7" "$Chan8"}

Mass00={"0.000"}
Mass00b={"0.050"}
Mass01={"0.100"}
Mass01b={"0.150"}
Mass02={"0.200"}
Mass02b={"0.250"}
Mass03={"0.300"}
Mass03b={"0.350"}
Mass04={"0.400"}
Mass04b={"0.450"}
Mass05={"0.500"}
Mass06={"0.600"}
Mass07={"0.700"}
Mass08={"0.800"}
Mass09={"0.900"}
Mass10={"1.000"}
Mass11={"1.100"}
Mass12={"1.200"}
Mass13={"1.300"}
Mass14={"1.400"}
Mass15={"1.500"}
Mass16={"1.600"}
Mass17={"1.700"}
Mass18={"1.800"}
Mass19={"1.900"}

MassArr={"$Mass00" "$Mass00b" "$Mass01" "$Mass01b" "$Mass02"
	 "$Mass02b" "$Mass03" "$Mass03b" "$Mass04" "$Mass04b"
	 "$Mass05" "$Mass06" "$Mass07" "$Mass08" "$Mass09"
	 "$Mass10" "$Mass11" "$Mass12" "$Mass13" "$Mass14"
	 "$Mass15" "$Mass16" "$Mass17" "$Mass18" "$Mass19"}

for i in "${ChanArr[@]}"
do
	for m in "${MassArr[@]}"
	do
		echo $Exec $Opt0 -o Results/$i"_dirac.root"    -c $i -m $m --dirac

		if [ "${m}" = "${MassArr[24]}" ]
		then
			 $Exec $Opt0 -o Results/$i"_dirac.root" -c $i -m $m --dirac &
		else
			 $Exec $Opt0 -o Results/$i"_dirac.root" -c $i -m $m --dirac
		fi

		echo $Exec $Opt0 -o Results/$i"_majorana.root" -c $i -m $m --majorana

		if [ "${m}" = "${MassArr[24]}" ]
		then
			 $Exec $Opt0 -o Results/$i"_majorana.root" -c $i -m $m --majorana &
		else
			 $Exec $Opt0 -o Results/$i"_majorana.root" -c $i -m $m --majorana
		fi
	done
done
