#!/bin/bash

cd /mt/home/tboschi/Templates/MCflux/Supershock

#Ue
./bin/Eps2Dat -i Limits/ps191Ue_1.dat -o Limits/lim_ps191Ue_1.dat --x1 0.01 --x2 100 --y1 1e-9 --y2 1e0
./bin/Eps2Dat -i Limits/ps191Ue_2.dat -o Limits/lim_ps191Ue_2.dat --x1 0.01 --x2 100 --y1 1e-9 --y2 1e0
./bin/Eps2Dat -i Limits/ps191Ue_3.dat -o Limits/lim_ps191Ue_3.dat --x1 0.01 --x2 100 --y1 1e-9 --y2 1e0
./bin/Eps2Dat -i Limits/peakUe.dat -o Limits/lim_peakUe.dat --x1 0.01 --x2 100 --y1 1e-9 --y2 1e0
./bin/Eps2Dat -i Limits/charmUe.dat -o Limits/lim_charmUe.dat --x1 0.01 --x2 100 --y1 1e-9 --y2 1e0

#Um
./bin/Eps2Dat -i Limits/ps191Um.dat -o Limits/lim_ps101Um.dat --x1 0.1 --x2 100 --y1 1e-9 --y2 1e0
./bin/Eps2Dat -i Limits/peakUm.dat -o Limits/lim_peakUm.dat --x1 0.1 --x2 100 --y1 1e-9 --y2 1e0
./bin/Eps2Dat -i Limits/charmUm.dat -o Limits/lim_charmUm.dat --x1 0.1 --x2 100 --y1 1e-9 --y2 1e0
