#!/bin/bash

cd /mt/home/tboschi/Templates/MCflux/Supershock

./bin/Rate -d config/ND_FGT -x ../numu_argon_xsec.root -f data/NuMu_0.root -o data/Rate_FGT_NuMu.dat
./bin/Rate -d config/ND_FGT -x ../nue_argon_xsec.root -f data/NuE_0.root -o data/Rate_FGT_NuE.dat
./bin/Rate -d config/ND_FGT -x ../nubar_argon_xsec.root -f data/NuBar_0.root -o data/Rate_FGT_NuBar.dat
