#!/bin/bash

cd /mt/home/tboschi/Templates/MCflux/Supershock

./bin/Plotter -i Exclusion/LAr2/LAr_MUPI_M_0.dat -o Exclusion/Plot_LAr2/MUPI_M_0.dat -t 2.44
./bin/Plotter -i Exclusion/LAr2/LAr_nMUMU_M_0.dat -o Exclusion/Plot_LAr2/nMUMU_M_0.dat -t 2.44
./bin/Plotter -i Exclusion/LAr2/LAr_nMUE_M_0.dat -o Exclusion/Plot_LAr2/nMUE_M_0.dat -t 2.44
./bin/Plotter -i Exclusion/LAr2/LAr_nEE_M_0.dat -o Exclusion/Plot_LAr2/nEE_M_0.dat -t 2.44
./bin/Plotter -i Exclusion/LAr2/LAr_nGAMMA_M_0.dat -o Exclusion/Plot_LAr2/nGAMMA_M_0.dat -t 2.44
./bin/Plotter -i Exclusion/LAr2/LAr_nPI0_M_0.dat -o Exclusion/Plot_LAr2/nPI0_M_0.dat -t 2.44

./bin/Plotter -i Exclusion/LAr2/LAr_EPI_E_0.dat -o Exclusion/Plot_LAr2/EPI_E_0.dat -t 2.44
./bin/Plotter -i Exclusion/LAr2/LAr_nMUMU_E_0.dat -o Exclusion/Plot_LAr2/nMUMU_E_0.dat -t 2.44
./bin/Plotter -i Exclusion/LAr2/LAr_nMUE_E_0.dat -o Exclusion/Plot_LAr2/nMUE_E_0.dat -t 2.44
./bin/Plotter -i Exclusion/LAr2/LAr_nEE_E_0.dat -o Exclusion/Plot_LAr2/nEE_E_0.dat -t 2.44
./bin/Plotter -i Exclusion/LAr2/LAr_nGAMMA_E_0.dat -o Exclusion/Plot_LAr2/nGAMMA_E_0.dat -t 2.44
./bin/Plotter -i Exclusion/LAr2/LAr_nPI0_E_0.dat -o Exclusion/Plot_LAr2/nPI0_E_0.dat -t 2.44
