#!/bin/bash

cd /mt/home/tboschi/Templates/MCflux/Supershock

./bin/Plotter -i Exclusion/FGT/FGT_MUPI_M_B.dat -o Exclusion/Plot_FGT/MUPI_M_B.dat -t -28.3269 -m 185.11 -A 0.25 -B 0.35
./bin/Plotter -i Exclusion/FGT/FGT_nEE_M_B.dat -o Exclusion/Plot_FGT/nEE_M_B.dat -t 11.9906 -m 3.3144 -A 0.05 -B 0.35
./bin/Plotter -i Exclusion/FGT/FGT_nMUE_M_B.dat -o Exclusion/Plot_FGT/nMUE_M_B.dat -t 25.0697 -m 13.2461 -A 0.15 -B 0.35
./bin/Plotter -i Exclusion/FGT/FGT_nMUMU_M_B.dat -o Exclusion/Plot_FGT/nMUMU_M_B.dat -t 49.0559 -m 51.9738 -A 0.25 -B 0.35
./bin/Plotter -i Exclusion/FGT/FGT_nGAMMA_M_B.dat -o Exclusion/Plot_FGT/nGAMMA_M_B.dat -t 47.6569 -m -58.0033 -A 0.05 -B 0.35
./bin/Plotter -i Exclusion/FGT/FGT_nPI0_M_B.dat -o Exclusion/Plot_FGT/nPI0_M_B.dat -t -20.6483 -m 163.968 -A 0.15 -B 0.35

./bin/Plotter -i Exclusion/FGT/FGT_EPI_E_B.dat -o Exclusion/Plot_FGT/EPI_E_B.dat -t 11.2859 -m 7.48414 -A 0.15 -B 0.45
./bin/Plotter -i Exclusion/FGT/FGT_nEE_E_B.dat -o Exclusion/Plot_FGT/nEE_E_B.dat -t 11.9906 -m 3.3144 -A 0.05 -B 0.45
./bin/Plotter -i Exclusion/FGT/FGT_nMUE_E_B.dat -o Exclusion/Plot_FGT/nMUE_E_B.dat -t 25.0697 -m 13.2461 -A 0.15 -B 0.45
./bin/Plotter -i Exclusion/FGT/FGT_nMUMU_E_B.dat -o Exclusion/Plot_FGT/nMUMU_E_B.dat -t 49.0559 -m 51.9738 -A 0.25 -B 0.45
./bin/Plotter -i Exclusion/FGT/FGT_nGAMMA_E_B.dat -o Exclusion/Plot_FGT/nGAMMA_E_B.dat -t 47.6569 -m -58.0033 -A 0.05 -B 0.45
./bin/Plotter -i Exclusion/FGT/FGT_nPI0_E_B.dat -o Exclusion/Plot_FGT/nPI0_E_B.dat -t -20.6483 -m 163.968 -A 0.15 -B 0.45

