#!/bin/bash

cd /mt/home/tboschi/Templates/MCflux/Supershock

./bin/Exclusion -s config/SMConfig -d config/ND_FGT_20 -f config/FluxConfig -o Exclusion/FGT_20/FGT_MUPI_M_0.dat -M -c MUPI
./bin/Exclusion -s config/SMConfig -d config/ND_FGT_20 -f config/FluxConfig -o Exclusion/FGT_20/FGT_nMUMU_M_0.dat -M -c nMUMU
./bin/Exclusion -s config/SMConfig -d config/ND_FGT_20 -f config/FluxConfig -o Exclusion/FGT_20/FGT_nMUE_M_0.dat -M -c nMUE
./bin/Exclusion -s config/SMConfig -d config/ND_FGT_20 -f config/FluxConfig -o Exclusion/FGT_20/FGT_nEE_M_0.dat -M -c nEE
./bin/Exclusion -s config/SMConfig -d config/ND_FGT_20 -f config/FluxConfig -o Exclusion/FGT_20/FGT_nGAMMA_M_0.dat -M -c nGAMMA
./bin/Exclusion -s config/SMConfig -d config/ND_FGT_20 -f config/FluxConfig -o Exclusion/FGT_20/FGT_nPI0_M_0.dat -M -c nPI0

./bin/Exclusion -s config/SMConfig -d config/ND_FGT_20 -f config/FluxConfig -o Exclusion/FGT_20/FGT_EPI_E_0.dat -E -c EPI
./bin/Exclusion -s config/SMConfig -d config/ND_FGT_20 -f config/FluxConfig -o Exclusion/FGT_20/FGT_nMUMU_E_0.dat -E -c nMUMU
./bin/Exclusion -s config/SMConfig -d config/ND_FGT_20 -f config/FluxConfig -o Exclusion/FGT_20/FGT_nMUE_E_0.dat -E -c nEMU
./bin/Exclusion -s config/SMConfig -d config/ND_FGT_20 -f config/FluxConfig -o Exclusion/FGT_20/FGT_nEE_E_0.dat -E -c nEE
./bin/Exclusion -s config/SMConfig -d config/ND_FGT_20 -f config/FluxConfig -o Exclusion/FGT_20/FGT_nGAMMA_E_0.dat -E -c nGAMMA
./bin/Exclusion -s config/SMConfig -d config/ND_FGT_20 -f config/FluxConfig -o Exclusion/FGT_20/FGT_nPI0_E_0.dat -E -c nPI0

