#!/bin/bash

cd /mt/home/tboschi/Templates/MCflux/Supershock

./bin/Exclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr/LAr_MUPI_M_B.dat -M -c MUPI -W
./bin/Exclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr/LAr_nMUMU_M_B.dat -M -c nMUMU -W
./bin/Exclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr/LAr_nMUE_M_B.dat -M -c nMUE -W
./bin/Exclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr/LAr_nEE_M_B.dat -M -c nEE -W
./bin/Exclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr/LAr_nGAMMA_M_B.dat -M -c nGAMMA -W
./bin/Exclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr/LAr_nPI0_M_B.dat -M -c nPI0 -W

./bin/Exclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr/LAr_EPI_E_B.dat -E -c EPI -W
./bin/Exclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr/LAr_nMUMU_E_B.dat -E -c nMUMU -W
./bin/Exclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr/LAr_nMUE_E_B.dat -E -c nEMU -W
./bin/Exclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr/LAr_nEE_E_B.dat -E -c nEE -W
./bin/Exclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr/LAr_nGAMMA_E_B.dat -E -c nGAMMA -W
./bin/Exclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr/LAr_nPI0_E_B.dat -E -c nPI0 -W
