#!/bin/bash

cd /mt/home/tboschi/scratch/Supershock

./bin/Plotter -i Exclusion/LAr/LAr_nnn_T.dat -o Exclusion/Plot_LAr/nnn_T.dat -t 2.44
./bin/Plotter -i Exclusion/LAr/LAr_nGAMMA_T.dat -o Exclusion/Plot_LAr/nGAMMA_T.dat -t 2.44
./bin/Plotter -i Exclusion/LAr/LAr_nEE_T.dat -o Exclusion/Plot_LAr/nEE_T.dat -t 2.44
#./bin/Plotter -i Exclusion/LAr/LAr_nEMU_T.dat -o Exclusion/Plot_LAr/nEMU_T.dat -t 2.44
#./bin/Plotter -i Exclusion/LAr/LAr_nMUE_T.dat -o Exclusion/Plot_LAr/nMUE_T.dat -t 2.44
./bin/Plotter -i Exclusion/LAr/LAr_nMUMU_T.dat -o Exclusion/Plot_LAr/nMUMU_T.dat -t 2.44
#./bin/Plotter -i Exclusion/LAr/LAr_nET_T.dat -o Exclusion/Plot_LAr/nET_T.dat -t 2.44
./bin/Plotter -i Exclusion/LAr/LAr_nTE_T.dat -o Exclusion/Plot_LAr/nTE_T.dat -t 2.44
#./bin/Plotter -i Exclusion/LAr/LAr_nMUT_T.dat -o Exclusion/Plot_LAr/nMUT_T.dat -t 2.44
./bin/Plotter -i Exclusion/LAr/LAr_nTMU_T.dat -o Exclusion/Plot_LAr/nTMU_T.dat -t 2.44
./bin/Plotter -i Exclusion/LAr/LAr_nPI0_T.dat -o Exclusion/Plot_LAr/nPI0_T.dat -t 2.44
#./bin/Plotter -i Exclusion/LAr/LAr_EPI_T.dat -o Exclusion/Plot_LAr/EPI_T.dat -t 2.44
#./bin/Plotter -i Exclusion/LAr/LAr_MUPI_T.dat -o Exclusion/Plot_LAr/MUPI_T.dat -t 2.44
./bin/Plotter -i Exclusion/LAr/LAr_TPI_T.dat -o Exclusion/Plot_LAr/TPI_T.dat -t 2.44
#./bin/Plotter -i Exclusion/LAr/LAr_EKA_T.dat -o Exclusion/Plot_LAr/EKA_T.dat -t 2.44
#./bin/Plotter -i Exclusion/LAr/LAr_MUKA_T.dat -o Exclusion/Plot_LAr/MUKA_T.dat -t 2.44
./bin/Plotter -i Exclusion/LAr/LAr_nRHO0_T.dat -o Exclusion/Plot_LAr/nRHO0_T.dat -t 2.44
#./bin/Plotter -i Exclusion/LAr/LAr_ERHO_T.dat -o Exclusion/Plot_LAr/ERHO_T.dat -t 2.44
#./bin/Plotter -i Exclusion/LAr/LAr_MURHO_T.dat -o Exclusion/Plot_LAr/MURHO_T.dat -t 2.44
#./bin/Plotter -i Exclusion/LAr/LAr_EKAx_T.dat -o Exclusion/Plot_LAr/EKAx_T.dat -t 2.44
./bin/Plotter -i Exclusion/LAr/LAr_nKA0x_T.dat -o Exclusion/Plot_LAr/nKA0x_T.dat -t 2.44
#./bin/Plotter -i Exclusion/LAr/LAr_MUKAx_T.dat -o Exclusion/Plot_LAr/MUKAx_T.dat -t 2.44
./bin/Plotter -i Exclusion/LAr/LAr_nOMEGA_T.dat -o Exclusion/Plot_LAr/nOMEGA_T.dat -t 2.44
./bin/Plotter -i Exclusion/LAr/LAr_nETA_T.dat -o Exclusion/Plot_LAr/nETA_T.dat -t 2.44
./bin/Plotter -i Exclusion/LAr/LAr_nETAi_T.dat -o Exclusion/Plot_LAr/nETAi_T.dat -t 2.44
./bin/Plotter -i Exclusion/LAr/LAr_nPHI_T.dat -o Exclusion/Plot_LAr/nPHI_T.dat -t 2.44
#./bin/Plotter -i Exclusion/LAr/LAr_ECHARM_T.dat -o Exclusion/Plot_LAr/ECHARM_T.dat -t 2.44
