#!/bin/bash

cd /mt/home/tboschi/Templates/MCflux/Supershock

./bin/Exclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr_MUPI_M_0.dat -M -c MUPI
./bin/Exclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr_nMUMU_M_0.dat -M -c nMUMU
./bin/Exclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr_nMUE_M_0.dat -M -c nMUE
./bin/Exclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr_nEE_M_0.dat -M -c nEE
./bin/Exclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr_nGAMMA_M_0.dat -M -c nGAMMA
./bin/Exclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr_nPI0_M_0.dat -M -c nPI0

./bin/Exclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr_EPI_E_0.dat -E -c EPI
./bin/Exclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr_nMUMU_E_0.dat -E -c nMUMU
./bin/Exclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr_nMUE_E_0.dat -E -c nEMU
./bin/Exclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr_nEE_E_0.dat -E -c nEE
./bin/Exclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr_nGAMMA_E_0.dat -E -c nGAMMA
./bin/Exclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr_nPI0_E_0.dat -E -c nPI0
