#!/bin/bash

cd /mt/home/tboschi/Templates/MCflux/Supershock

./bin/Plotter -i Exclusion/LAr/LAr_MUPI_M_0.dat -o Exclusion/Plot_LAr/MUPI_M_0.dat -t 2.44
./bin/Plotter -i Exclusion/LAr/LAr_nMUMU_M_0.dat -o Exclusion/Plot_LAr/nMUMU_M_0.dat -t 2.44
./bin/Plotter -i Exclusion/LAr/LAr_nMUE_M_0.dat -o Exclusion/Plot_LAr/nMUE_M_0.dat -t 2.44
./bin/Plotter -i Exclusion/LAr/LAr_nEE_M_0.dat -o Exclusion/Plot_LAr/nEE_M_0.dat -t 2.44
./bin/Plotter -i Exclusion/LAr/LAr_nGAMMA_M_0.dat -o Exclusion/Plot_LAr/nGAMMA_M_0.dat -t 2.44
./bin/Plotter -i Exclusion/LAr/LAr_nPI0_M_0.dat -o Exclusion/Plot_LAr/nPI0_M_0.dat -t 2.44

./bin/Plotter -i Exclusion/LAr/LAr_EPI_E_0.dat -o Exclusion/Plot_LAr/EPI_E_0.dat -t 2.44
./bin/Plotter -i Exclusion/LAr/LAr_nMUMU_E_0.dat -o Exclusion/Plot_LAr/nMUMU_E_0.dat -t 2.44
./bin/Plotter -i Exclusion/LAr/LAr_nMUE_E_0.dat -o Exclusion/Plot_LAr/nMUE_E_0.dat -t 2.44
./bin/Plotter -i Exclusion/LAr/LAr_nEE_E_0.dat -o Exclusion/Plot_LAr/nEE_E_0.dat -t 2.44
./bin/Plotter -i Exclusion/LAr/LAr_nGAMMA_E_0.dat -o Exclusion/Plot_LAr/nGAMMA_E_0.dat -t 2.44
./bin/Plotter -i Exclusion/LAr/LAr_nPI0_E_0.dat -o Exclusion/Plot_LAr/nPI0_E_0.dat -t 2.44
