#!/bin/bash

cd /mt/home/tboschi/scratch/Supershock

#./bin/Coupler -A Exclusion/LAr/LAr_nnn_T.dat -B Exclusion/FGT/FGT_nnn_T.dat -o Exclusion/Couple/nnn_T.dat
./bin/Coupler -A Exclusion/LAr/LAr_nGAMMA_T.dat -B Exclusion/FGT/FGT_nGAMMA_T.dat -o Exclusion/Couple/nGAMMA_T.dat
./bin/Coupler -A Exclusion/LAr/LAr_nEE_T.dat -B Exclusion/FGT/FGT_nEE_T.dat -o Exclusion/Couple/nEE_T.dat
#./bin/Coupler -A Exclusion/LAr/LAr_nEMU_T.dat -B Exclusion/FGT/FGT_nEMU_T.dat -o Exclusion/Couple/nEMU_T.dat
#./bin/Coupler -A Exclusion/LAr/LAr_nMUE_T.dat -B Exclusion/FGT/FGT_nMUE_T.dat -o Exclusion/Couple/nMUE_T.dat
./bin/Coupler -A Exclusion/LAr/LAr_nMUMU_T.dat -B Exclusion/FGT/FGT_nMUMU_T.dat -o Exclusion/Couple/nMUMU_T.dat
#./bin/Coupler -A Exclusion/LAr/LAr_nET_T.dat -B Exclusion/FGT/FGT_nET_T.dat -o Exclusion/Couple/nET_T.dat
./bin/Coupler -A Exclusion/LAr/LAr_nTE_T.dat -B Exclusion/FGT/FGT_nTE_T.dat -o Exclusion/Couple/nTE_T.dat
#./bin/Coupler -A Exclusion/LAr/LAr_nMUT_T.dat -B Exclusion/FGT/FGT_nMUT_T.dat -o Exclusion/Couple/nMUT_T.dat
./bin/Coupler -A Exclusion/LAr/LAr_nTMU_T.dat -B Exclusion/FGT/FGT_nTMU_T.dat -o Exclusion/Couple/nTMU_T.dat
./bin/Coupler -A Exclusion/LAr/LAr_nPI0_T.dat -B Exclusion/FGT/FGT_nPI0_T.dat -o Exclusion/Couple/nPI0_T.dat
#./bin/Coupler -A Exclusion/LAr/LAr_EPI_T.dat -B Exclusion/FGT/FGT_EPI_T.dat -o Exclusion/Couple/EPI_T.dat
#./bin/Coupler -A Exclusion/LAr/LAr_MUPI_T.dat -B Exclusion/FGT/FGT_MUPI_T.dat -o Exclusion/Couple/MUPI_T.dat
./bin/Coupler -A Exclusion/LAr/LAr_TPI_T.dat -B Exclusion/FGT/FGT_TPI_T.dat -o Exclusion/Couple/TPI_T.dat
#./bin/Coupler -A Exclusion/LAr/LAr_EKA_T.dat -B Exclusion/FGT/FGT_EKA_T.dat -o Exclusion/Couple/EKA_T.dat
#./bin/Coupler -A Exclusion/LAr/LAr_MUKA_T.dat -B Exclusion/FGT/FGT_MUKA_T.dat -o Exclusion/Couple/MUKA_T.dat
./bin/Coupler -A Exclusion/LAr/LAr_nRHO0_T.dat -B Exclusion/FGT/FGT_nRHO0_T.dat -o Exclusion/Couple/nRHO0_T.dat
#./bin/Coupler -A Exclusion/LAr/LAr_ERHO_T.dat -B Exclusion/FGT/FGT_ERHO_T.dat -o Exclusion/Couple/ERHO_T.dat
#./bin/Coupler -A Exclusion/LAr/LAr_MURHO_T.dat -B Exclusion/FGT/FGT_MURHO_T.dat -o Exclusion/Couple/MURHO_T.dat
#./bin/Coupler -A Exclusion/LAr/LAr_EKAx_T.dat -B Exclusion/FGT/FGT_EKAx_T.dat -o Exclusion/Couple/EKAx_T.dat
./bin/Coupler -A Exclusion/LAr/LAr_nKA0x_T.dat -B Exclusion/FGT/FGT_nKA0x_T.dat -o Exclusion/Couple/nKA0x_T.dat
#./bin/Coupler -A Exclusion/LAr/LAr_MUKAx_T.dat -B Exclusion/FGT/FGT_MUKAx_T.dat -o Exclusion/Couple/MUKAx_T.dat
./bin/Coupler -A Exclusion/LAr/LAr_nOMEGA_T.dat -B Exclusion/FGT/FGT_nOMEGA_T.dat -o Exclusion/Couple/nOMEGA_T.dat
./bin/Coupler -A Exclusion/LAr/LAr_nETA_T.dat -B Exclusion/FGT/FGT_nETA_T.dat -o Exclusion/Couple/nETA_T.dat
./bin/Coupler -A Exclusion/LAr/LAr_nETAi_T.dat -B Exclusion/FGT/FGT_nETAi_T.dat -o Exclusion/Couple/nETAi_T.dat
./bin/Coupler -A Exclusion/LAr/LAr_nPHI_T.dat -B Exclusion/FGT/FGT_nPHI_T.dat -o Exclusion/Couple/nPHI_T.dat
#./bin/Coupler -A Exclusion/LAr/LAr_ECHARM_T.dat -B Exclusion/FGT/FGT_ECHARM_T.dat -o Exclusion/Couple/ECHARM_T.dat
