#!/bin/bash

cd /mt/home/tboschi/Templates/MCflux/Supershock

./bin/Plotter -i Exclusion/Couple/MUPI_M_0.dat -o Exclusion/Plot_Couple/MUPI_M_0.dat -t 2.44
./bin/Plotter -i Exclusion/Couple/nMUMU_M_0.dat -o Exclusion/Plot_Couple/nMUMU_M_0.dat -t 2.44
./bin/Plotter -i Exclusion/Couple/nMUE_M_0.dat -o Exclusion/Plot_Couple/nMUE_M_0.dat -t 2.44
./bin/Plotter -i Exclusion/Couple/nEE_M_0.dat -o Exclusion/Plot_Couple/nEE_M_0.dat -t 2.44
./bin/Plotter -i Exclusion/Couple/nGAMMA_M_0.dat -o Exclusion/Plot_Couple/nGAMMA_M_0.dat -t 2.44
./bin/Plotter -i Exclusion/Couple/nPI0_M_0.dat -o Exclusion/Plot_Couple/nPI0_M_0.dat -t 2.44

./bin/Plotter -i Exclusion/Couple/EPI_E_0.dat -o Exclusion/Plot_Couple/EPI_E_0.dat -t 2.44
./bin/Plotter -i Exclusion/Couple/nMUMU_E_0.dat -o Exclusion/Plot_Couple/nMUMU_E_0.dat -t 2.44
./bin/Plotter -i Exclusion/Couple/nMUE_E_0.dat -o Exclusion/Plot_Couple/nMUE_E_0.dat -t 2.44
./bin/Plotter -i Exclusion/Couple/nEE_E_0.dat -o Exclusion/Plot_Couple/nEE_E_0.dat -t 2.44
./bin/Plotter -i Exclusion/Couple/nGAMMA_E_0.dat -o Exclusion/Plot_Couple/nGAMMA_E_0.dat -t 2.44
./bin/Plotter -i Exclusion/Couple/nPI0_E_0.dat -o Exclusion/Plot_Couple/nPI0_E_0.dat -t 2.44
