#!/bin/bash --login

#$ -S /bin/bash
#$ -cwd
#$ -N HLNExclusion
#$ -t 1-26
# -M tommaso.boschi@qmul.ac.uk
# -m e
#$ -l h_rss=4G,h_vmem=4G 
#$ -q "SL6@heppc400,SL6@heppc401,SL6@heppc402,SL6@heppc403,SL6@heppc404,SL6@heppc405,SL6@heppc406,SL6@heppc407"

#source /opt/sge/default/common/settings.sh
#source /users/tboschi/.bashrc
#echo $ROOTSYS
#echo $PATH
#export $LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/lib64:/usr/lib64:$ROOTSYS/lib:$G4LIB:$CUBA/lib"

#Home="/data/tboschi/NewSupershock/"
#cd $HOME

Exec="./bin/FastExclusion"

#Channel=$(./EchoChannel $SGE_TASK_ID)
Channel=$(./EchoChannel $1)
Config="-d config/ND_Full -f config/FluxConfig"

#dirac particle
Opt00=("--dirac -P -L -E -M")
Opt01=("--dirac -P -L -M -T")
Opt02=("--dirac -P -L -T -E")
Opt03=("--dirac -P -L -E -M -T")
Opt04=("--dirac -P -R -E -M")
Opt05=("--dirac -P -R -M -T")
Opt06=("--dirac -P -R -T -E")
Opt07=("--dirac -P -R -E -M -T")
Opt08=("--dirac -P -E -M")
Opt09=("--dirac -P -M -T")
Opt10=("--dirac -P -T -E")
Opt11=("--dirac -P -E -M -T")

#dirac antiparticle
Opt12=("--dirac -A -L -E -M")
Opt13=("--dirac -A -L -M -T")
Opt14=("--dirac -A -L -T -E")
Opt15=("--dirac -A -L -E -M -T")
Opt16=("--dirac -A -R -E -M")
Opt17=("--dirac -A -R -M -T")
Opt18=("--dirac -A -R -T -E")
Opt19=("--dirac -A -R -E -M -T")
Opt20=("--dirac -A -E -M")
Opt21=("--dirac -A -M -T")
Opt22=("--dirac -A -T -E")
Opt23=("--dirac -A -E -M -T")

#dirac both
Opt24=("--dirac -L -E -M")
Opt25=("--dirac -L -M -T")
Opt26=("--dirac -L -T -E")
Opt27=("--dirac -L -E -M -T")
Opt28=("--dirac -R -E -M")
Opt29=("--dirac -R -M -T")
Opt30=("--dirac -R -T -E")
Opt31=("--dirac -R -E -M -T")
Opt32=("--dirac -E -M")
Opt33=("--dirac -M -T")
Opt34=("--dirac -T -E")
Opt35=("--dirac -E -M -T")
 
#majorana
Opt36=("--majorana -L -E -M")
Opt37=("--majorana -L -M -T")
Opt38=("--majorana -L -T -E")
Opt39=("--majorana -L -E -M -T")
Opt40=("--majorana -R -E -M")
Opt41=("--majorana -R -M -T")
Opt42=("--majorana -R -T -E")
Opt43=("--majorana -R -E -M -T")
Opt44=("--majorana -E -M")
Opt45=("--majorana -M -T")
Opt46=("--majorana -T -E")
Opt47=("--majorana -E -M -T")

OptA_0=("$Opt00" "$Opt01" "$Opt02" "$Opt03" "$Opt04" "$Opt05" "$Opt06" "$Opt07" "$Opt08" "$Opt09" "$Opt10" "$Opt11"
	"$Opt12" "$Opt13" "$Opt14" "$Opt15" "$Opt16" "$Opt17" "$Opt18" "$Opt19" "$Opt20" "$Opt21" "$Opt22" "$Opt23")
OptA_1=("$Opt24" "$Opt25" "$Opt26" "$Opt27" "$Opt28" "$Opt29" "$Opt30" "$Opt31" "$Opt32" "$Opt33" "$Opt34" "$Opt35"
	"$Opt36" "$Opt37" "$Opt38" "$Opt39" "$Opt40" "$Opt41" "$Opt42" "$Opt43" "$Opt44" "$Opt45" "$Opt46" "$Opt47")

# Run the tasks:
#first array
for i in "${OptA_0[@]}"
do
	echo $Exec $Config -o Results/Exclusion/$Channel -c $Channel "${i}"

	if [ "${i}" = "${OptA_0[@]: -1}" ]
	then
		$Exec $Config -o Results/Exclusion/$Channel -c $Channel ${i}
	else
		$Exec $Config -o Results/Exclusion/$Channel -c $Channel ${i} &
	fi
done
#second array
for i in "${OptA_1[@]}"
do
	echo $Exec $Config -o Results/Exclusion/$Channel -c $Channel "${i}"

	if [ "${i}" = "${OptA_1[@]: -1}" ]
	then
		$Exec $Config -o Results/Exclusion/$Channel -c $Channel ${i}
	else
		$Exec $Config -o Results/Exclusion/$Channel -c $Channel ${i} &
	fi
done
