#!/bin/bash --login

Config="config"

Exec="./bin/DecayBranch"

cc00=("nEM")
cc01=("nET")
cc02=("nMT")
cc03=("EPI")
cc04=("MPI")
cc05=("TPI")
cc06=("EKA")
cc07=("MKA")
cc08=("ERHO")
cc09=("MRHO")
cc10=("EKAx")
cc11=("MKAx")
cc12=("ECHARM")

nc00=("nnn")
nc01=("nGAMMA")
nc02=("nEE")
nc03=("nMM")
nc04=("nPI0")
nc05=("nRHO0")
nc06=("nOMEGA")
nc07=("nETA")
nc08=("nETAi")
nc09=("nPHI")
nc10=("ExpALL")

ccArr=("$cc00" "$cc01" "$cc02" "$cc03" "$cc04" "$cc05" "$cc06" "$cc07" "$cc08" "$cc09" "$cc10" "$cc11" "$cc12")
ncArr=("$nc00" "$nc01" "$nc02" "$nc03" "$nc04" "$nc05" "$nc06" "$nc07" "$nc08" "$nc09" "$nc10")

# Run the tasks:
for i in "${ccArr[@]}"
do
	echo $Exec -o Results/Kinematic/"Branch_"${i}".dat" -c "${i}" -E -M -T

	if [ "${i}" = "${ccArr[12]}" ]
	then
		$Exec -o Results/Kinematic/"Branch_"${i}".dat" -c "${i}" -E -M -T
	else
		$Exec -o Results/Kinematic/"Branch_"${i}".dat" -c "${i}" -E -M -T &
	fi
done

for i in "${ncArr[@]}"
do
	echo $Exec -o Results/Kinematic/"Branch_"${i}".dat" -c "${i}" -E -M -T

	if [ "${i}" = "${ncArr[10]}" ]
	then
		$Exec -o Results/Kinematic/"Branch_"${i}".dat" -c "${i}" -E -M -T
	else
		$Exec -o Results/Kinematic/"Branch_"${i}".dat" -c "${i}" -E -M -T &
	fi
done
