#!/bin/bash --login

Config="config"

Exec="./bin/Simulation"

#Channel=$(./EchoChannel $1)
Opt0="-d config/ND_Full -f config/FluxConfig"

Chan1=("nEE")
Chan2=("nEM")
#Chan3=("nME")
Chan4=("nMM")
Chan5=("nGAMMA")
Chan6=("nPI0")
Chan7=("EPI")
Chan8=("MPI")

ChanArr=("$Chan1" "$Chan2" "$Chan4" "$Chan5" "$Chan6" "$Chan7" "$Chan8")
#ChanArr=("$Chan6")

#Mass00=("0.000")
Mass005=("0.050")
Mass010=("0.100")
Mass015=("0.150")
Mass020=("0.200")
Mass025=("0.250")
Mass030=("0.300")
Mass035=("0.350")
Mass040=("0.400")
Mass045=("0.450")
Mass050=("0.500")
Mass055=("0.500")
Mass060=("0.600")
Mass070=("0.700")
Mass080=("0.800")
Mass090=("0.900")
Mass100=("1.000")
Mass110=("1.100")
Mass120=("1.200")
Mass130=("1.300")
Mass140=("1.400")
Mass150=("1.500")
Mass160=("1.600")
Mass170=("1.700")
Mass180=("1.800")
#Mass190=("1.900")

MassArr=("$Mass005" "$Mass010" "$Mass015" "$Mass020" "$Mass025"
	 "$Mass030" "$Mass035" "$Mass040" "$Mass045" "$Mass050" 
	 "$Mass055" "$Mass060" "$Mass070" "$Mass080" "$Mass090" 
	 "$Mass100" "$Mass110" "$Mass120" "$Mass130" "$Mass140"
	 "$Mass150" "$Mass160" "$Mass170" "$Mass180" )
	 #"$Mass190")

for i in "${ChanArr[@]}"
do
	for m in "${MassArr[@]}"
	do
		echo $Exec $Opt0 -o Results/Simulation/$i -c $i -m $m --dirac

		if [ "${m}" = "${MassArr[23]}" ]
		then
			 $Exec $Opt0 -o Results/Simulation/$i -c $i -m $m --dirac
		else
			 $Exec $Opt0 -o Results/Simulation/$i -c $i -m $m --dirac &
		fi
	done

	for m in "${MassArr[@]}"
	do
		echo $Exec $Opt0 -o Results/Simulation/$i -c $i -m $m --majorana

		if [ "${m}" = "${MassArr[23]}" ]
		then
			 $Exec $Opt0 -o Results/Simulation/$i -c $i -m $m --majorana
		else
			 $Exec $Opt0 -o Results/Simulation/$i -c $i -m $m --majorana &
		fi
	done
done
