#!/bin/bash --login

Config="config"

Exec="./bin/ProductionScale"

ch2_0=("PionE")
ch2_1=("PionM")
ch2_2=("KaonE")
ch2_3=("KaonM")
ch2_4=("CharmE")
ch2_5=("CharmM")
ch2_6=("CharmT")
ch2_7=("TauPI")

ChanTwo=("$ch2_0" "$ch2_1" "$ch2_2" "$ch2_3" "$ch2_4" "$ch2_5" "$ch2_6" "$ch2_7")

ch3_0=("MuonE")
ch3_1=("MuonM")
ch3_2=("TauEE")
ch3_3=("TauET")
ch3_4=("TauMM")
ch3_5=("TauMT")
ch3_6=("Tau2PI")
ch3_7=("Kaon0E")
ch3_8=("Kaon0M")
ch3_9=("KaonCE")
ch310=("KaonCM")

ChanThree=("$ch3_0" "$ch3_1" "$ch3_2" "$ch3_3" "$ch3_4" "$ch3_5" "$ch3_6" "$ch3_7" "$ch3_8" "$ch3_9" "$ch310")

# Run the tasks:
for i in "${ChanTwo[@]}"
do
	echo $Exec -o Results/Kinematic/"Kine_2"${i}".dat" -c "${i}"

	if [ "${i}" = "${OptArr[7]}" ]
	then
		$Exec -o Results/Kinematic/"Kine_2"${i}".dat" -c "${i}"
	else
		$Exec -o Results/Kinematic/"Kine_2"${i}".dat" -c "${i}" &
	fi
done

for i in "${ChanThree[@]}"
do
	echo $Exec -o Results/Kinematic/"Kine_2"${i}".dat" -c "${i}"

	if [ "${i}" = "${OptThree[10]}" ]
	then
		$Exec -o Results/Kinematic/"Kine_2"${i}".dat" -c "${i}"
	else
		$Exec -o Results/Kinematic/"Kine_2"${i}".dat" -c "${i}" &
	fi
done
