#!/bin/bash --login

#$ -S /bin/bash
#$ -cwd
#$ -N HLNExclusion
#$ -t 1-26
# -M tommaso.boschi@qmul.ac.uk
# -m e
#$ -l h_rss=4G,h_vmem=4G 
#$ -q "SL6@heppc400,SL6@heppc401,SL6@heppc402,SL6@heppc403,SL6@heppc404,SL6@heppc405,SL6@heppc406,SL6@heppc407"

#source /opt/sge/default/common/settings.sh
#source /users/tboschi/.bashrc
#echo $ROOTSYS
#echo $PATH
#export $LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/lib64:/usr/lib64:$ROOTSYS/lib:$G4LIB:$CUBA/lib"

#Home="/data/tboschi/NewSupershock/"
#cd $HOME

Exec="./bin/FastExclusion"

#Channel=$(./EchoChannel $SGE_TASK_ID)
Channel=$(./EchoChannel $1)
Config="-d config/ND_Full -f config/FluxConfig"

#dirac particle
Opt00=("--dirac -P -L -E")
Opt01=("--dirac -P -L -M")
Opt02=("--dirac -P -L -T")
Opt03=("--dirac -P -R -E")
Opt04=("--dirac -P -R -M")
Opt05=("--dirac -P -R -T")
Opt06=("--dirac -P -E")
Opt07=("--dirac -P -M")
Opt08=("--dirac -P -T")

#dirac antiparticle
Opt09=("--dirac -A -L -E")
Opt10=("--dirac -A -L -M")
Opt11=("--dirac -A -L -T")
Opt12=("--dirac -A -R -E")
Opt13=("--dirac -A -R -M")
Opt14=("--dirac -A -R -T")
Opt15=("--dirac -A -E")
Opt16=("--dirac -A -M")
Opt17=("--dirac -A -T")

#dirac both
Opt18=("--dirac -L -E")
Opt19=("--dirac -L -M")
Opt20=("--dirac -L -T")
Opt21=("--dirac -R -E")
Opt22=("--dirac -R -M")
Opt23=("--dirac -R -T")
Opt24=("--dirac -E")
Opt25=("--dirac -M")
Opt26=("--dirac -T")
 
#majorana
Opt27=("--majorana -L -E")
Opt28=("--majorana -L -M")
Opt29=("--majorana -L -T")
Opt30=("--majorana -R -E")
Opt31=("--majorana -R -M")
Opt32=("--majorana -R -T")
Opt33=("--majorana -E")
Opt34=("--majorana -M")
Opt35=("--majorana -T")

#splitting array to ease cpu overload
OptA_0=("$Opt00" "$Opt01" "$Opt02" "$Opt03" "$Opt04" "$Opt05" "$Opt06" "$Opt07" "$Opt08"
	"$Opt09" "$Opt10" "$Opt11" "$Opt12" "$Opt13" "$Opt14" "$Opt15" "$Opt16" "$Opt17")
OptA_1=("$Opt18" "$Opt19" "$Opt20" "$Opt21" "$Opt22" "$Opt23" "$Opt24" "$Opt25" "$Opt26"
	"$Opt27" "$Opt28" "$Opt29" "$Opt30" "$Opt31" "$Opt32" "$Opt33" "$Opt34" "$Opt35")

# Run the tasks:
#first array
for i in "${OptA_0[@]}"
do
	echo $Exec $Config -o Results/Exclusion/$Channel -c $Channel "${i}"

	if [ "${i}" = "${OptA_0[@]: -1}" ]
	then
		$Exec $Config -o Results/Exclusion/$Channel -c $Channel ${i}
	else
		$Exec $Config -o Results/Exclusion/$Channel -c $Channel ${i} &
	fi
done
#second array
for i in "${OptA_1[@]}"
do
	echo $Exec $Config -o Results/Exclusion/$Channel -c $Channel "${i}"

	if [ "${i}" = "${OptA_1[@]: -1}" ]
	then
		$Exec $Config -o Results/Exclusion/$Channel -c $Channel ${i}
	else
		$Exec $Config -o Results/Exclusion/$Channel -c $Channel ${i} &
	fi
done
