#!/bin/bash

./bin/Efficiency -i Results/Efficiency/eff_EPI_dirac.list   -o Results/Efficiency/EPI_dirac.root
./bin/Efficiency -i Results/Efficiency/eff_MPI_dirac.list   -o Results/Efficiency/MPI_dirac.root
./bin/Efficiency -i Results/Efficiency/eff_nEE_dirac.list    -o Results/Efficiency/nEE_dirac.root
./bin/Efficiency -i Results/Efficiency/eff_nME_dirac.list   -o Results/Efficiency/nME_dirac.root
./bin/Efficiency -i Results/Efficiency/eff_nMM_dirac.list  -o Results/Efficiency/nMM_dirac.root
./bin/Efficiency -i Results/Efficiency/eff_nGAMMA_dirac.list -o Results/Efficiency/nGAMMA_dirac.root
./bin/Efficiency -i Results/Efficiency/eff_nPI0_dirac.list   -o Results/Efficiency/nPI0_dirac.root

./bin/Efficiency -i Results/Efficiency/eff_EPI_major.list   -o Results/Efficiency/EPI_major.root
./bin/Efficiency -i Results/Efficiency/eff_MPI_major.list   -o Results/Efficiency/MPI_major.root
./bin/Efficiency -i Results/Efficiency/eff_nEE_major.list    -o Results/Efficiency/nEE_major.root
./bin/Efficiency -i Results/Efficiency/eff_nME_major.list   -o Results/Efficiency/nME_major.root
./bin/Efficiency -i Results/Efficiency/eff_nMM_major.list  -o Results/Efficiency/nMM_major.root
./bin/Efficiency -i Results/Efficiency/eff_nGAMMA_major.list -o Results/Efficiency/nGAMMA_major.root
./bin/Efficiency -i Results/Efficiency/eff_nPI0_major.list   -o Results/Efficiency/nPI0_major.root
